name: Deploy Strapi

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.19.1'

      - name: Install dependencies
        run: npm install

      - name: Build Strapi
        run: yarn build

      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
          KEY: ${{ secrets.EC2_KEY }}
        run: |
          ssh -i $KEY $USER@$HOST "cd /home/ubuntu/strapi && git pull && yarn install && yarn build && pm2 restart strapi"

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
          KEY: ${{ secrets.EC2_KEY }}
        run: |
          ssh -i $KEY $USER@$HOST "cd /home/ubuntu/strapi && yarn develop"
